ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ com.smartcampus.backend.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5433/smartcampus"
    driver = "org.postgresql.Driver"
    user = "postgres"
    password = "123456"
    maxPoolSize = 10
}

jwt {
    secret = "smart-campus-secret-key-change-in-production-2024"
    issuer = "smart-campus-backend"
    audience = "smart-campus-app"
    realm = "Smart Campus"
    expirationMs = 86400000
}

rapidapi {
    key = "32a19255damshd002d37962f8893p1a5f1bjsnf0e922258f0c"
    host = "jsearch.p.rapidapi.com"
}

